global names f txts txtsopt scrsz btnopt btnopen btnopenmat;
scrsz = get(groot,'ScreenSize');

%% новое
x0=scrsz(3);%ширина экрана
y0=scrsz(4);%высота
xf=320; %основного окна
yf=150;
f = figure('Name','Optimization','Resize','off','MenuBar','None','Position',[(x0-xf)/2 (y0-yf)/2 xf yf]);
names='Файл до оптимизации: ';

 xb=60;%кнопок
 yb=25;

btnmainhelp = uicontrol('Style','pushbutton','Parent',f,...
        'Position',[xf-xb yf-yb xb yb],...
        'String','Help', 'Callback', {@btnmainhelpclick});
btnopendec = uicontrol('Style','pushbutton','Parent',f,...
        'Position',[1 yf-yb xb+20 yb],...
        'String','Decomposer', 'Callback', {@btnopendecclick}); 
    
btnopen = uicontrol('Style','pushbutton','Parent',f,...
        'Position',[20 yf-2.5*yb xb yb],...
        'String','Open', 'Callback', {@btnopenclick});

btnopenmat = uicontrol('Style','pushbutton','Parent',f,...
        'Position',[20 yf-4*yb xb yb],...
        'String','Matrix', 'Callback', {@btnopenmatclick});
    
btnopt = uicontrol('Style','pushbutton','Parent',f,...
        'Position',[20 yf-5.5*yb xb yb],...
        'String','Optimize!', 'Callback', {@btnoptclick},'Visible','off');
    
txts = uicontrol('Style','text','Parent',f,...
        'Position',[25+xb yf-2.5*yb xf-20-xb yb/1.5],...
        'HorizontalAlignment','left','String',names);
txtsopt = uicontrol('Style','text','Parent',f,...
        'Position',[25+xb yf-5.5*yb xf-20-xb yb/1.5],...
        'HorizontalAlignment','left','String','Файл после оптимизации: ','Visible','off');
   